Update android-cicd.yml
Creates google-services.json from secret

diff --git a/.github/workflows/android-cicd.yml b/.github/workflows/android-cicd.yml
--- a/.github/workflows/android-cicd.yml
+++ b/.github/workflows/android-cicd.yml
@@ -10,6 +10,18 @@ jobs:
     runs-on: ubuntu-latest
 
     steps:
+      - name: Create google-services from secret
+        env:
+          GOOGLE_SERVICES_JSON_CONTENT: ${{ secrets.GOOGLE_SERVICES_JSON }}
+        run: |
+          REPO_NAME:$(echo "$GITHUB_REPOSITORY" | cut -d'/' -f2)
+          TARGET_PATH:"/home/runner/$REPO_NAME/$REPO_NAME/app/google-services.json"
+          if [-f "$FILE_PATH"]; then
+            cat "$FILE_PATH" | base64
+          else
+            echo "File not found $FILE_PATH"
+            exit 1
+          fi
       # Checkout the code
       - name: Checkout code
         uses: actions/checkout@v4
